# Generated by Django 3.1 on 2020-09-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200907_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='title',
            new_name='book',
        ),
    ]
